#! /bin/bash

os_info=$(cat /etc/os-release)

echo "\"server\":{"

name=$(echo "$os_info" | grep "NAME" | head -n 1 | cut -d '=' -f 2)
echo \        \"name\":"$name"

version=$(echo "$os_info" | grep "VERSION" | head -n 1 | cut -d '=' -f 2)
echo \        \"version\":\""$version"\"

echo },
